const products = [
  {
    name: "Laptop Pro X1",
    description: "High-performance laptop for professionals.",
    count: 100,
    price: 1299.99,
    rating: 4.5,
    reviewsNumber: 50,
    sales: 200,
    attrs: [
      { key: "Processor", value: "Intel Core i7" },
      { key: "RAM", value: "16GB" },
      { key: "Storage", value: "512GB SSD" },
    ],
    images: [
      { path: "/images/laptop-pro-x1-1.jpg" },
      { path: "/images/laptop-pro-x1-2.jpg" },
    ],
    category: "Electronics",
    reviews: [],
  },
  {
    name: "Wireless Mouse M2",
    description: "Ergonomic wireless mouse for comfortable use.",
    count: 500,
    price: 29.99,
    rating: 4.2,
    reviewsNumber: 150,
    sales: 800,
    attrs: [
      { key: "Connectivity", value: "2.4GHz Wireless" },
      { key: "Buttons", value: "6" },
      { key: "DPI", value: "1600" },
    ],
    images: [
      { path: "/images/mouse-m2-1.jpg" },
      { path: "/images/mouse-m2-2.jpg" },
    ],
    category: "Electronics",
    reviews: [],
  },
  {
    name: "4K Monitor 27-inch",
    description: "High-resolution 4K monitor for stunning visuals.",
    count: 50,
    price: 399.99,
    rating: 4.8,
    reviewsNumber: 80,
    sales: 150,
    attrs: [
      { key: "Resolution", value: "3840x2160" },
      { key: "Refresh Rate", value: "60Hz" },
      { key: "Panel Type", value: "IPS" },
    ],
    images: [
      { path: "/images/monitor-4k-1.jpg" },
      { path: "/images/monitor-4k-2.jpg" },
    ],
    category: "Electronics",
    reviews: [],
  },
  {
    name: "Mechanical Keyboard K3",
    description: "Tactile mechanical keyboard for gaming and typing.",
    count: 200,
    price: 89.99,
    rating: 4.6,
    reviewsNumber: 120,
    sales: 400,
    attrs: [
      { key: "Switches", value: "Cherry MX Brown" },
      { key: "Layout", value: "ANSI" },
      { key: "Backlighting", value: "RGB" },
    ],
    images: [
      { path: "/images/keyboard-k3-1.jpg" },
      { path: "/images/keyboard-k3-2.jpg" },
    ],
    category: "Electronics",
    reviews: [],
  },
  {
    name: "External SSD 1TB",
    description: "Fast and reliable external SSD for data storage.",
    count: 300,
    price: 149.99,
    rating: 4.7,
    reviewsNumber: 90,
    sales: 500,
    attrs: [
      { key: "Capacity", value: "1TB" },
      { key: "Interface", value: "USB 3.2 Gen 2" },
      { key: "Read Speed", value: "1000MB/s" },
    ],
    images: [
      { path: "/images/ssd-1tb-1.jpg" },
      { path: "/images/ssd-1tb-2.jpg" },
    ],
    category: "Electronics",
    reviews: [],
  },
  {
    name: "Cotton T-Shirt",
    description: "Comfortable cotton t-shirt for everyday wear.",
    count: 1000,
    price: 19.99,
    rating: 4.3,
    reviewsNumber: 200,
    sales: 1500,
    attrs: [
      { key: "Material", value: "100% Cotton" },
      { key: "Size", value: "Various" },
      { key: "Color", value: "Various" },
    ],
    images: [
      { path: "/images/tshirt-1.jpg" },
      { path: "/images/tshirt-2.jpg" },
    ],
    category: "Clothing",
    reviews: [],
  },
  {
    name: "Board Game: Settlers",
    description: "Classic strategy board game for the whole family.",
    count: 200,
    price: 39.99,
    rating: 4.8,
    reviewsNumber: 150,
    sales: 600,
    attrs: [
      { key: "Players", value: "3-4" },
      { key: "Age", value: "10+" },
    ],
    images: [{ path: "/images/settlers.jpg" }],
    category: "Games",
    reviews: [],
  },
  {
    name: "Basketball",
    description: "Official size basketball for indoor and outdoor play.",
    count: 500,
    price: 24.99,
    rating: 4.5,
    reviewsNumber: 100,
    sales: 800,
    attrs: [{ key: "Size", value: "Official" }],
    images: [{ path: "/images/basketball.jpg" }],
    category: "Sports and Outdoors",
    reviews: [],
  },
  {
    name: "Camping Tent",
    description: "Waterproof and durable camping tent for 4 people.",
    count: 100,
    price: 149.99,
    rating: 4.7,
    reviewsNumber: 80,
    sales: 300,
    attrs: [{ key: "Capacity", value: "4 Person" }],
    images: [{ path: "/images/camping-tent.jpg" }],
    category: "Sports and Outdoors",
    reviews: [],
  },
  {
    name: "Stainless Steel Cookware Set",
    description: "12-piece stainless steel cookware set for everyday cooking.",
    count: 300,
    price: 199.99,
    rating: 4.6,
    reviewsNumber: 120,
    sales: 500,
    attrs: [{ key: "Pieces", value: "12" }],
    images: [{ path: "/images/cookware-set.jpg" }],
    category: "Home and Kitchen",
    reviews: [],
  },
  {
    name: "The Lord of the Rings",
    description: "J.R.R. Tolkien's epic fantasy trilogy.",
    count: 800,
    price: 29.99,
    rating: 5,
    reviewsNumber: 200,
    sales: 1000,
    attrs: [{ key: "Author", value: "J.R.R. Tolkien" }],
    images: [{ path: "/images/lord-of-the-rings.jpg" }],
    category: "Books",
    reviews: [],
  },
  {
    name: "Instant Pot",
    description: "Multi-functional electric pressure cooker.",
    count: 250,
    price: 99.99,
    rating: 4.7,
    reviewsNumber: 180,
    sales: 600,
    attrs: [{ key: "Functions", value: "Various" }],
    images: [{ path: "/images/instant-pot.jpg" }],
    category: "Home and Kitchen",
    reviews: [],
  },
  {
    name: "Chess Set",
    description: "Wooden chess set with hand-carved pieces.",
    count: 150,
    price: 49.99,
    rating: 4.6,
    reviewsNumber: 120,
        sales: 300,
        attrs: [{ key: "Material", value: "Wood" }],
        images: [{ path: "/images/chess-set.jpg" }],
        category: "Games",
        reviews: [],
      },
      {
        name: "Running Shoes",
        description: "Lightweight and comfortable running shoes for men and women.",
        count: 400,
        price: 79.99,
        rating: 4.4,
        reviewsNumber: 180,
        sales: 700,
        attrs: [{ key: "Type", value: "Running" }],
        images: [{ path: "/images/running-shoes.jpg" }],
        category: "Sports and Outdoors",
        reviews: [],
      },
      {
        name: "Hiking Backpack",
        description: "Durable and spacious hiking backpack with multiple compartments.",
        count: 150,
        price: 129.99,
        rating: 3.2,
        reviewsNumber: 90,
        sales: 400,
        attrs: [{ key: "Capacity", value: "40L" }],
        images: [{ path: "/images/hiking-backpack.jpg" }],
        category: "Sports and Outdoors",
        reviews: [],
      },
      {
        name: "Cookbook: Italian Recipes",
        description: "A collection of authentic Italian recipes for all skill levels.",
        count: 600,
        price: 24.99,
        rating: 3,
        reviewsNumber: 150,
        sales: 900,
        attrs: [{ key: "Cuisine", value: "Italian" }],
        images: [{ path: "/images/italian-cookbook.jpg" }],
        category: "Books",
        reviews: [],
      },
      {
        name: "Coffee Maker",
        description: "Automatic drip coffee maker with a timer and carafe.",
        count: 400,
        price: 59.99,
        rating: 3,
        reviewsNumber: 120,
        sales: 700,
        attrs: [{ key: "Capacity", value: "12 cups" }],
        images: [{ path: "/images/coffee-maker.jpg" }],
        category: "Home and Kitchen",
        reviews: [],
      },
      {
        name: "The Chronicles of Narnia",
        description: "C.S. Lewis' classic fantasy series for children and adults.",
        count: 700,
        price: 29.99,
        rating: 5,
        reviewsNumber: 180,
        sales: 1200,
        attrs: [{ key: "Author", value: "C.S. Lewis" }],
        images: [{ path: "/images/narnia.jpg" }],
        category: "Books",
        reviews: [],
      },
    ];

module.exports = products